action_id: trunk-upgrade-available
date: 2024-02-03 19:36:07
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\r\n"
  err: ""
timestamp: 1706988967
full_timestamp:
  nanos: 674918000
  seconds: 1706988967
trunk_version: 1.19.0
